# Generated by Django 4.1.3 on 2022-11-10 09:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phn_number', models.CharField(max_length=100)),
                ('mpesa_code', models.CharField(max_length=100)),
                ('package', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2022, 11, 10, 9, 7, 44, 521400, tzinfo=datetime.timezone.utc))),
                ('amount', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('paid_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ui_name', models.CharField(max_length=200)),
                ('amount', models.IntegerField(default=0)),
                ('code', models.CharField(max_length=100)),
                ('investment_period', models.IntegerField(default=0)),
                ('percentage_return', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phn_number', models.CharField(max_length=100)),
                ('amount', models.IntegerField(default=0)),
                ('fee', models.IntegerField(default=0)),
                ('withdrawn_by', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2022, 11, 10, 9, 7, 44, 521617, tzinfo=datetime.timezone.utc))),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phn_number', models.CharField(max_length=100)),
                ('amount', models.IntegerField(default=0)),
                ('withdrawn_by', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2022, 11, 10, 9, 7, 44, 521794, tzinfo=datetime.timezone.utc))),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=12)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('recommended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
