# Generated by Django 4.1.3 on 2022-11-16 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0002_alter_payment_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 7, 33, 49, 404667, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 7, 33, 49, 404873, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='withdrawreferral',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 7, 33, 49, 405051, tzinfo=datetime.timezone.utc)),
        ),
    ]
