# Generated by Django 4.1.3 on 2022-11-21 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0003_alter_payment_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 7, 33, 48, 721620, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 7, 33, 48, 721823, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='withdrawreferral',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 7, 33, 48, 722001, tzinfo=datetime.timezone.utc)),
        ),
    ]
